server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: boleta-ms
          uri: lb://boleta
          predicates:
            - Path=/api/v1/boletas/**
        - id: carrito-ms
          uri: lb://carrito
          predicates:
            - Path=/api/v1/carritos/**
        - id: catalogo-ms
          uri: lb://catalogo
          predicates:
            - Path=/api/v1/catalogos/**
        - id: clientes-ms
          uri: lb://clientes
          predicates:
            - Path=/api/v1/clientes/**
        - id: compra-ms
          uri: lb://compra
          predicates:
            - Path=/api/v1/compras/**
        - id: contactos-ms
          uri: lb://contactos
          predicates:
            - Path=/api/v1/contactos/**
        - id: intercambio-ms
          uri: lb://intercambio
          predicates:
            - Path=/api/v1/intercambios/**
        - id: modificacion-ms
          uri: lb://modificacion
          predicates:
            - Path=/api/v1/modificaciones/**
        - id: torneo-ms
          uri: lb://torneo
          predicates:
            - Path=/api/v1/torneos/**
        - id: venta-ms
          uri: lb://venta
          predicates:
            - Path=/api/v1/ventas/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/